name: Deploy to Oracle Compute

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Frontend 빌드
      - name: Install dependencies & Build React
        run: |
          cd frontend
          npm install
          npm run type-check
          npm run build

      # Backend 빌드
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot app
        run: |
          cd backend
          chmod +x ./gradlew
          rm -rf ~/.gradle/caches
          ./gradlew build -x test

      - name: 파일 목록 확인
        run: |
          ls -la frontend/dist
          ls -la backend/build/libs

      # 서버에 배포 (Frontend & Backend)
      - name: Set up Docker container with rsync
        uses: docker/setup-buildx-action@v2

      - name: Deploy to Oracle Compute Instance using rsync
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -e SSH_KEY="${{ secrets.OCI_SSH_PRIVATE_KEY }}" -e HOST="${{ secrets.OCI_COMPUTE_HOST }}" -e USER="ubuntu" \
            ubuntu:latest bash -c "
              mkdir -p /root/.ssh && \
              echo \"$SSH_KEY\" > /root/.ssh/id_rsa && \
              chmod 600 /root/.ssh/id_rsa && \
              rsync -avz /workspace/frontend/dist/ $USER@$HOST:~/deploy/frontend/ && \
              rsync -avz /workspace/backend/build/libs/*.jar $USER@$HOST:~/deploy/backend/
            "
      - name: Restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_COMPUTE_HOST }}
          username: ubuntu
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          script: |
            # 프론트엔드 배포
            sudo rm -rf /var/www/frontend
            sudo mv ~/deploy/frontend /var/www/frontend
            sudo systemctl restart nginx

            # 백엔드 실행
            pkill -f 'java -jar' || true
            nohup java -jar ~/deploy/backend/backend-*.jar > ~/deploy/backend/backend.log 2>&1 &