name: Deploy to Oracle Compute

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Enable pnpm and check version
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm --version  # 설치 확인용

      # Frontend 빌드
      - name: Install dependencies & Build React
        run: |
          cd frontend
          pnpm install
          pnpm run build

      # Backend 빌드
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot app
        run: |
          cd backend
          ./gradlew build -x test

      # 서버에 배포 (Frontend & Backend)
      - name: Deploy to Oracle Compute Instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.OCI_COMPUTE_HOST }}
          username: ubuntu
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          source: |
            frontend/build/*
            backend/build/libs/*.jar
          target: "~/deploy"

      - name: Restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_COMPUTE_HOST }}
          username: ubuntu
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          script: |
            # 프론트엔드 배포
            sudo rm -rf /var/www/frontend
            sudo mv ~/deploy /var/www/frontend
            sudo systemctl restart nginx

            # 백엔드 실행
            pkill -f 'java -jar' || true
            nohup java -jar ~/deploy/backend-*.jar > ~/deploy/backend.log 2>&1 &