name: Deploy Spring Boot and Frontend

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: wheon06/yeoun-backend:latest

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: wheon06/yeoun-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]

    steps:
      - name: Deploy backend via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.OCI_COMPUTE_HOST }}
          username: ${{ secrets.OCI_SSH_USER }}
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          port: ${{ secrets.OCI_SSH_PORT }}
          script: |
            export DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            export DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            export DATABASE_USER=${{ secrets.DATABASE_USER }}
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            export DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            export JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}
            export JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
            docker pull wheon06/yeoun-backend:latest
            docker stop yeoun-backend || true
            docker rm yeoun-backend || true
            docker run -d --name yeoun-backend -p 8080:8080 \
            -e DATABASE_HOST=$DATABASE_HOST \
            -e DATABASE_PORT=$DATABASE_PORT \
            -e DATABASE_USER=$DATABASE_USER \
            -e DATABASE_PASSWORD=$DATABASE_PASSWORD \
            -e DATABASE_NAME=$DATABASE_NAME \
            -e JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET \
            -e JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET \
            wheon06/yeoun-backend:latest

      - name: Deploy frontend via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.OCI_COMPUTE_HOST }}
          username: ${{ secrets.OCI_SSH_USER }}
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          port: ${{ secrets.OCI_SSH_PORT }}
          script: |
            docker pull wheon06/yeoun-frontend:latest
            docker stop yeoun-frontend || true
            docker rm yeoun-frontend || true
            docker run -d --name yeoun-frontend -p 80:80 wheon06/yeoun-frontend:latest