name: Deploy Spring Boot and Frontend

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: wheon06/yeoun-backend:latest

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: wheon06/yeoun-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]

    steps:
      - name: Deploy backend via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.OCI_COMPUTE_HOST }}
          username: ${{ secrets.OCI_SSH_USER }}
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          port: ${{ secrets.OCI_SSH_PORT }}
          script: |
            mkdir -p ~/backend/config
            echo "${{ secrets.APPLICATION }}" > ~/backend/config/application.yml
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ~/backend/config/keystore.p12
            cat ~/backend/config/application.yml
            docker pull wheon06/yeoun-backend:latest
            docker stop yeoun-backend || true
            docker rm yeoun-backend || true
            docker run -d --name yeoun-backend \
              -p 8080:8080 \
              -v ~/backend/config/application.yml:/app/config/application.yml \
              -v ~/backend/config/keystore.p12:/app/config/keystore.p12 \
              wheon06/yeoun-backend:latest

      - name: Deploy frontend via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.OCI_COMPUTE_HOST }}
          username: ${{ secrets.OCI_SSH_USER }}
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          port: ${{ secrets.OCI_SSH_PORT }}
          script: |
            docker pull wheon06/yeoun-frontend:latest
            docker stop yeoun-frontend || true
            docker rm yeoun-frontend || true
            docker run -d --name yeoun-frontend -p 80:80 wheon06/yeoun-frontend:latest